apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: CB services build
on:
  push:
    branches:
      - '**'

jobs:
  build:
    steps:
      - name: Build
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "Build"
